export default function TermsOfServicePage() {
  return (
    <div className="min-h-screen bg-c4p text-gray-900">
      <div className="mx-auto max-w-4xl px-6 py-12">
        <div className="bg-white shadow-xl rounded-2xl p-8">
          <header className="mb-10">
            <h1 className="text-4xl font-extrabold tracking-tight">Terms of Service</h1>
            <p className="text-sm text-gray-500 mt-2">Last updated [September 23rd], 2025</p>
          </header>

          <article className="prose prose-zinc max-w-none">
            <h2>Agreement to the Terms</h2>
            <p>
              These Terms of Service, including any policies and other terms that are incorporated herein by reference (collectively, these “Terms”), constitute a legally binding agreement made between you, whether personally or on behalf of an entity (“you,” or “your”) and Computers For People, Inc. (“we,” “us,” or “our”), governing your access to and use of our websites (our “Sites”), social media, and other online platforms or services (together with our Sites, collectively, our “Online Services”), our offline services, programs, and events operated by or in partnership with us (collectively, our “Offline Services”), and all of the content that our Online Services and Offline Services contain, or may in the future contain, including but not limited to text, content, photographs, video, audio and audiovisual works, graphics, products, services, goods, designs, artwork, information, applications, software, music, audio files, articles, directories, guides, photographs, code and data, together with all trademarks, service marks, trade names, trade dress, copyrights, logos, domain names, and/or any other form of Intellectual Property Rights (as defined below) included therein or embodied thereby (as defined below) (collectively, our “Content”, and together with the Online Services and the Offline Services, the “Services”). In addition to these Terms, your access to and use of certain portions or aspects of the Services may require you accept additional terms or conditions, which are hereby incorporated and made a part of these Terms by this reference.
            </p>
            <p>
              PLEASE REVIEW THESE TERMS CAREFULLY. BY ACCESSING OR USING THE SERVICES, REGISTERING FOR THE SERVICES, YOU ACCEPT AND AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE TO BE BOUND BY THESE TERMS, YOU SHOULD NOT REGISTER FOR, ACCESS OR USE THE SERVICES.
            </p>
            <p>
              We reserve the right to modify these Terms at any time, and such modifications shall be effective immediately upon posting to our Online Services. Please continue to review these Terms whenever accessing, linking to, or using the Services. Your access to or use of the Services after the posting of modifications to these Terms will constitute your acceptance of these Terms, as modified. By accessing or using the Services, you agree that we may collect, process, and disclose your personal information in accordance with our Privacy Policy, available at [www.computers4people.org/privacypolicy]. IF, AT ANY TIME, YOU DO NOT AGREE TO ANY TERMS OR CONDITIONS OF THESE TERMS, OR ANY OTHER TERMS, CONDITIONS OR POLICIES INCORPORATED HEREIN OR LINKED HERETO, INCLUDING OUR PRIVACY POLICY, YOU SHOULD STOP ACCESSING OR USING THE SERVICES.
            </p>
            <p>
              ARBITRATION NOTICE. THESE TERMS CONTAIN AN ARBITRATION CLAUSE IN SECTION 15. YOU AND WE AGREE THAT, EXCEPT FOR CERTAIN TYPES OF DISPUTES MENTIONED IN THAT ARBITRATION CLAUSE, DISPUTES BETWEEN US WILL BE RESOLVED BY MANDATORY BINDING ARBITRATION, AND YOU AND WE WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS-ACTION LAWSUIT OR CLASS-WIDE ARBITRATION, AND ANY RIGHT TO TRIAL BY JURY. YOU HAVE THE RIGHT TO OPT OUT OF ARBITRATION AS EXPLAINED IN THAT ARBITRATION CLAUSE.
            </p>
            <p>
              If you are accessing or using the Services on behalf of an entity or other organization that is the end user of the Services, then you are agreeing to these Terms for that entity or organization and representing to us that you have the authority to bind such entity or organization to these Terms (and, in which case, the terms “you” and “your” will refer to that entity or organization).
            </p>
            <p>
              [We are committed to helping those with disabilities access the Sites. We strive to provide an excellent online experience for all our visitors – including those with sight, hearing and other disabilities, in compliance with the Americans with Disabilities Act (ADA) and Web Content Accessibility Guidelines (WCAG). If you have difficulty using or accessing any element of the Sites, please contact us using the contact information below.]
            </p>
            <p>
              You represent and warrant that you are at least eighteen (18) years old or have reached the age of majority in your jurisdiction. If you have not reached the age of majority in your jurisdiction, you may only use the Services if your parent or guardian consents to your use of the Services, assumes the obligations provided in these Terms and assumes full responsibility for your use of the Services.
            </p>
            <p>
              The Services are intended to comply with U.S. state and federal laws and regulations, and are not intended for distribution to or use by any person or entity in any other jurisdiction or country if such distribution or use would be contrary to law or regulation or which would subject us to any regulatory requirement within such jurisdiction or country. Accordingly, those who access or use the Services from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the extent local laws are applicable.
            </p>

            <h2>Use and Use Restrictions; Intellectual Property Ownership; Feedback</h2>
            <h3>Use.</h3>
            <p>
              Subject to the terms and conditions under these Terms, you may access and use the Services in accordance with these Terms for your own personal, non-commercial use. You acquire absolutely no rights or licenses in or to the Services other than as expressly set forth in this Section 2(a), subject to the restrictions set forth in Section 2(b).
            </p>
            <h3>Use Restrictions.</h3>
            <p>The limited rights granted to you in Section 2(a) are subject to the following restrictions (collectively, the “Use Restrictions”):</p>
            <ul className="list-disc ml-6">
              <li>You may not use the Services for any illegal purpose, to facilitate the violation of any law or regulation, or in a manner inconsistent with these Terms.</li>
              <li>You may only use the Services for your own personal, non-commercial purposes and benefit and, if applicable, for your employer’s own non-commercial purposes and benefit.</li>
              <li>You may not use the Services to defraud or mislead other persons, including without limitation in any attempt to obtain sensitive information such as user passwords.</li>
              <li>You may not use the data made available on the Services, alone or in combination with any other data, in any manner that would identify any individual person, household, business or other entity.</li>
              <li>You may not copy, reproduce, recompile, decompile, disassemble, reverse engineer, distribute, publish, display, perform, modify, upload to, create derivative works from, transmit, download, or in any way exploit any part of the Services, except as expressly authorized in these Terms. You may download material from the Services and/or make a reasonable number of copies of the material from the Services for your own, personal non-commercial purposes and benefit and, if applicable, for your employer’s own non-commercial purposes and benefit, provided that you retain all copyright and other proprietary notices. The Services and the information contained therein may not be used to construct a database of any kind, nor may the Services be stored (in its entirety or in any part) in databases for access by you or any third party to distribute any database services containing all or part of the Services.</li>
              <li>You may not access, monitor, or copy any content or information on the Services using any robot, spider, scraper, web crawler, or other automated means or any similar manual process. You may not violate the restrictions in any robot exclusion headers on the Services, if any, or bypass or circumvent other measures employed to prevent or limit access to the Services. You may not violate the security of the Services or attempt to gain unauthorized access to the Services or computer systems or networks connected to the Services through any means.</li>
              <li>You may not upload or transmit (or attempt to upload or to transmit) viruses, Trojan horses, or other material that interferes with any person’s uninterrupted use and enjoyment of the Services or modifies, impairs, disrupts, alters, or interferes with the use, features, functions, operation, or maintenance of the Services.</li>
              <li>You may not use the Services or the information contained therein in connection with unsolicited mailings or spam material. You will not spam or send unsolicited mailings to any person or entity using the Services. You may use the external sharing functions (if any) solely to inform others about Content on the Services, and you shall immediately cease using these functions with regard to recipients who have requested not to receive such information.</li>
              <li>You may not frame the Services or any portion or page of the Services. You may not archive, cache, or mirror any page or portion of a page of the Services. You may not include a link(s) on your website or other online platforms to the Services (or any page or portion thereof) without our prior written permission. To request permission to link to the Services, you may contact us using the contact information below. If you receive permission to link to the Services, you may not link to the Services any website containing inappropriate, profane, defamatory, infringing, obscene, indecent, or unlawful topics, names, or material or information that violates any applicable Intellectual Property Rights (as defined below) or proprietary, privacy, or publicity rights. If you link to the Services, you may not portray any person or subject in a false or misleading light. In addition, you may not imply that we and/or our Suppliers (as defined below) are endorsing your commentary, products or services. Any violation of this provision may, in our discretion, result in termination of your access to and use of the Services effective immediately.</li>
              <li>You may not use the Services in any manner that could damage, disable, overburden or otherwise interfere with or impair the Services.</li>
              <li>You may not use the Services to harass, abuse, or harm another person, or to transmit any unlawful, threatening, abusive, libelous, defamatory, discriminatory, obscene, vulgar, pornographic, profane, lewd, lascivious or indecent information of any kind, including images and language.</li>
              <li>You may not transmit or solicit any information, software or other material that violates or infringes upon the rights of others, including material that is an invasion of privacy or publicity rights, is protected by copyright, trademark or other intellectual property or proprietary rights, or is a derivative work with respect thereto.</li>
              <li>You may not otherwise use the Services outside the scope expressly authorized hereunder.</li>
            </ul>
            
            <h3>Intellectual Property Ownership.</h3>
            <ul className="list-disc ml-6">
              <li>The Services are protected by Intellectual Property Rights and/or other proprietary rights and laws of the U.S. and other countries, including any international treaties. The Services are also protected as a collective work or compilation under U.S. copyright and other laws and treaties. All Content (including but not limited to source code, databases, functionalities, software, website designs, audio, video, text, photographs, graphics, articles) and other elements making up the Services are also copyrighted works. You agree to abide by all applicable copyright and other laws, as well as any additional copyright notices or restrictions contained in the Services.</li>
              <li>You acknowledge that the Services have been developed, compiled, prepared, revised, selected, and arranged by us and others, including, but not limited to, through the application of methods and standards of judgment developed and applied through the expenditure of substantial time, effort, and money and constitutes valuable Intellectual Property Rights of us and such others. You agree to protect the Intellectual Property Rights and other proprietary rights of us and all others having rights in the Services, including but not limited to us, during and after the term of these Terms and to comply with all reasonable written requests made by us or our partners, suppliers, licensors, and owners of content, copyrights, trademarks, or otherwise (our “Suppliers”), to protect our or their contractual, statutory, and common law rights in the Services.</li>
              <li>You agree to promptly notify us in writing using the contact information below upon becoming aware of any unauthorized access to or use of the Services by any individual or entity or of any claim that the Services infringe upon any Intellectual Property Rights, or other contractual, statutory, or common law rights.</li>
              <li>All present and future rights in and to trade secrets, patents, copyrights, trademarks, service marks, know-how, and other proprietary rights of any type under the laws of any governmental authority, domestic or foreign, including rights in and to all applications and registrations thereof (collectively, “Intellectual Property Rights”), relating to the Services shall at all times be and remain our or our licensors’ sole and exclusive property. Any and all present and future right, interest and title in and to the Services (including the right to exploit the Services and any portions of the Services over any present or future technology) are reserved to us for our exclusive use.</li>
            </ul>

            <h3>Feedback.</h3>
            <p>
              You may provide us with questions, comments, suggestions, ideas, feedback, or other information concerning the Services (“Feedback”). You agree that you will not provide any confidential, proprietary or personal information to us as Feedback. You further agree that we are the sole owner to all right, title and interest in the Feedback, and we and our designees will be free to use, copy, modify, create derivative works of, publicly display, disclose, distribute, license and sublicense, incorporate, and otherwise exploit the Feedback, including derivative works thereof, for any and all commercial and non-commercial purposes with no expectation of payment or attribution of any kind by you. You hereby waive all moral rights to any Feedback, and you hereby warrant that any Feedback is original to you or that you have the right to submit such Feedback. You agree there shall be no recourse against us for any alleged or actual infringement or misappropriation of any Intellectual Property Rights or other proprietary rights in your Feedback. We aim to respond to any inquiries you submit through our Sites in a timely manner but do not guarantee specific response times or outcomes, and you agree that any submission of or response to any such inquiries do not establish a relationship between you and us beyond the scope of these Terms unless expressly agreed otherwise in writing.
            </p>

            <h2>User Representations</h2>
            <p>
              By accessing or using the Services, you represent and warrant that: (i) all registration information and any other information you submit are true, accurate, current, and complete; (ii) you will maintain the accuracy of such information and promptly update such information as necessary; (iii) you have the legal capacity and you agree to comply with these Terms; (iv) you are at least eighteen (18) years old or have reached the age of majority in your jurisdiction, or if you have not reached the age of majority in your jurisdiction, you have received express permission from your parent or guardian to use the Services, and such parent or guardian have agreed to assume all your obligations set forth in these Terms and full responsibility for your access and use of the Services; (v) you will not access or use the Services in violation of the Use Restrictions, including but not limited to using the Services for any illegal or unauthorized purpose; (vi) you will comply with all applicable laws, rules and regulations; and (vii) you have the authority and capacity under the laws of the state or jurisdiction in which you reside to make the representations and warranties and be bound by the covenants and obligations provided herein.
            </p>

            <h2>Account Creation; Applications and Registrations</h2>
            <p>
              To use the Services or certain portions thereof, you may be required to create an account (including without limitation to make Purchases (as defined below)), or to submit application or registration forms (such as for Offline Services). As part of the account creation, application or registration process, you may be asked to provide your email address and other information and/or create a password, in which event you must provide true, accurate, current and complete information about yourself. If you provide any information that is untrue, inaccurate, not current, or incomplete, we have the right to suspend or terminate your account, reject your application, cancel your registration, and/or refuse any and all current or future use of the Services (or any portion thereof). You must also keep that information true, accurate, current and complete after you have created your account or submitted your application or registration. Each account, application or registration is for a single user only, unless otherwise expressly specified by us in writing. You may not register an account, submit an application or registration form, or otherwise use the Services, to impersonate any person or entity, or falsely state or otherwise misrepresent yourself. You agree to treat your account credentials (including, without limitation, your username, password and any other sensitive information) as confidential and not to disclose your them (or any portion thereof), either directly or indirectly, to any person.
            </p>
            <p>
              You are fully responsible for all usage and activity of the Services by you or anyone using your account or device, including, but not limited to, any use of your account credentials. Your account is personal to you and such access may not be shared with any other person. We reserve the right to terminate inactive or delinquent accounts with or without notice. You understand and agree that, if you cancel your account or withdraw an application or registration, we and third parties may retain copies of information provided by you in accordance with our Privacy Policy.
            </p>
            <p>
              You agree to notify us immediately using our contact information below of any known or suspected unauthorized use(s) of the Services, or any known or suspected breach of security, including but not limited to loss, theft, or unauthorized disclosure of your account credentials and other personal or sensitive information. WE SHALL NOT BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY LOSS OR DAMAGE ARISING FROM ANY UNAUTHORIZED USE OF THE SERVICES OR BREACH OF SECURITY. If a device on which the Services is accessed is sold or transferred to another party, you agree to delete all cookies and software files obtained by or through use of the Services that are stored on such device. Notwithstanding anything else herein, we reserve the right to pursue any and all claims against you and any person or entity using your account credentials. We may require you to change your account credentials. We reserve the right to suspend your account or access to the Services.
            </p>
            <p>
              We reserve the right to remove, reclaim, or change a username you select if we determine, in our sole discretion, that such username is inappropriate, obscene, or otherwise objectionable.
            </p>

            <h2>Purchases; Payment</h2>
            <h3>Purchases.</h3>
            <p>
              Certain Services require payment by you, and you also may be able to purchase certain products through the Services or through Third-Party Websites hosted or operated by our Suppliers at the then-current pricing displayed on the Services or such Third-Party Websites (as applicable) for the applicable product (collectively, “Purchases”). Any Purchases made on Third-Party Websites shall be subject to the applicable terms and conditions on such websites, and we disclaim any liability arising from any Purchases made through such Third-Party Websites. We reserve the right to modify the prices, terms and conditions, and availability for any Purchases available through our Services at any time without notice to you. We further reserve the right to refuse any Purchase transactions made through our Services for any reason.
            </p>
            <h3>Payment.</h3>
            <p>
              When you make a payment for any Purchases, you explicitly agree: (i) to pay the price listed for the applicable product, along with any additional amounts relating to applicable taxes, credit card fees, bank fees, transaction fees, and shipping fees; and (ii) to abide by any relevant terms of service, privacy policies, or other legal agreements or restrictions (including any age restrictions) imposed by us and our Suppliers, as applicable. You are responsible for all charges of Purchases incurred under your account made by you or anyone who accesses your account.
            </p>
            <ul className="list-disc ml-6">
              <li>All payments for Purchases available through our Services are final and not refundable or exchangeable, except as required by applicable law or as otherwise expressly set forth in our refund policy (if any). We make no guarantee as to the nature, quality, or value of the products or services provided in connection with any Purchases available through our Services or the availability or supply thereof.</li>
              <li>For clarity, you are responsible for and agree to pay any applicable taxes, duties, tariffs, and fees related to your Purchases, including those required to be paid to either us or any of our Suppliers. These taxes may include, but are not limited to, VAT, GST, sales tax, withholding tax, and any other applicable taxes. Depending on your location, we and our Suppliers may be responsible for collecting and reporting information related to transaction taxes arising from your Purchases. You grant us and our Suppliers permission to provide your account and personal information to relevant tax authorities to fulfill our or their tax collection and reporting obligations. Any Purchase made through the Services (and not through any Third-Party Websites) comply with the applicable Internal Revenue Service (IRS) guidelines for non-profit organizations. Any unrelated business income is managed in accordance with applicable tax laws to support our exempt purposes.</li>
              <li>Any private personal data that you provide in connection with your Purchases through the Services (and not through any Third-Party Websites) including, without limitation, any data provided in connection with payment, will be processed in accordance with our Privacy Policy. We may share your payment information with third parties to the extent necessary to process payments; prevent, detect, and investigate fraud or other prohibited activities; facilitate dispute resolution such as chargebacks or refunds; and for other purposes associated with the acceptance of credit cards, debit cards, or ACH.</li>
              <li>You are solely responsible for ensuring that your billing and payment information is correct at all times to prevent your Purchases from being cancelled. We will not be liable for any delay or non-delivery of payment, including without limitation any errors made or delays by you, your bank, your credit card company, and/or any payment network. If your payment method cannot be charged for any reason (such as expiration or insufficient funds), we may attempt to charge the payment method if you have updated your payment method information, or we may cancel your applicable Purchase.</li>
            </ul>
            <p>
              To make a Purchase, you represent and warrant that (i) you are not located in a country that is subject to a U.S. government embargo, or that has been designated by the U.S. government as a “terrorist supporting” country and (ii) you are not listed on any U.S. government list of prohibited or restricted parties.
            </p>

            <h2>Donations</h2>
            <p>
              You may choose to make donations to us through the Sites or other portions of the Services, whether on an one-time basis or a recurring basis. All such donations are voluntary and irrevocable; provided, that you may at any time modify the amount and frequency of, suspend or terminate any donations scheduled to be made on a recurring basis by providing us with prior written notice using the contact information below. Donations made are generally non-refundable, except in cases of processing errors or as required by law. Any refund requests will be evaluated at our sole discretion.
            </p>
            <p>
              Donations will be used to support our mission as described on our website at https://www.computers4people.org/about. We reserve the right to allocate funds to areas of greatest need within this mission.
            </p>
            <p>
              We are a 501(c)(3) non-profit organization, and as such donations may be tax-deductible to the extent permitted by applicable laws. We will provide tax receipts for qualified donations of two hundred fifty dollars ($250) or more. Please consult your tax advisor to determine eligibility, as we do not provide tax advice.
            </p>
            <p>
              By making a donation, you consent to us using your name and donation details (unless you opt for anonymity) for promotional purposes. You may opt out at any time by notifying us in writing using the contact information below. Without limiting and subject to the foregoing, any private personal data that you provide in connection with your donations, including, without limitation, any data provided in connection with payment, will be processed in accordance with our Privacy Policy. We may share your payment information with third parties to the extent necessary to process payments; prevent, detect, and investigate fraud or other prohibited activities; facilitate dispute resolution such as chargebacks or refunds; and for other purposes associated with the acceptance of credit cards, debit cards, or ACH.
            </p>
            <p>
              As a registered 501(c)(3) non-profit organization, we provide access to our financial reports (e.g., IRS Form 990) upon request or via our Sites. This ensures transparency in how we use resources to support our mission.
            </p>

            <h2>Mobile Services</h2>
            <p>
              Certain portion of the Services, including our Sites, are available via a mobile device. To the extent you access the Services through a mobile device, your wireless service carrier’s standard charges, data rates and other fees may apply. In addition, downloading, installing, or using certain Services, may be prohibited or restricted by your carrier, and not all Services may work with all carriers or devices. You agree that we may communicate with you by SMS, MMS, text message or other electronic means to your mobile device.
            </p>
            <p>
              You agree to receive automated marketing calls or texts (e.g., marketing, promotions, discounts, offers for products and/or services, etc.) from or on behalf of us at the phone number(s) you have provided to us. Such consent is not a condition of your access or use of our Services. You acknowledge that message frequency varies and that message and data rates may apply. You further acknowledge that certain of such calls or texts may be artificial and/or pre-recorded. You may opt out at any time by following the applicable instructions provided in such calls or texts.
            </p>

            <h2>Third-Party Website and Content</h2>
            <p>
              The Services may contain (or you may be sent via the Services) links to other websites (such as our social media accounts and other online services or platforms) (“Third-Party Websites”), as well as articles, photographs, text, graphics, pictures, designs, music, sound, video, advertisements, information, products, services, applications, software, and other content or items belonging to or originating from third parties (“Third-Party Content”). Such Third-Party Websites and Third-Party Content are not investigated, monitored, or checked for accuracy, appropriateness, or completeness by us, and we are not responsible for any Third-Party Websites accessed through the Services or any Third-Party Content posted on or available through the Services, including the content, accuracy, offensiveness, opinions, reliability, privacy practices, or other policies of or contained in the Third-Party Websites or the Third-Party Content. Inclusion of, linking to, or permitting the use of any Third-Party Websites or any Third-Party Content does not imply approval or endorsement thereof by us. If you decide to access the Third-Party Websites or to use or install any Third-Party Content, you do so at your own risk, and you should be aware these Terms do not govern such access or installation. You should review the applicable terms and policies, including privacy and data gathering practices, of any Third-Party Websites to which you navigate from the Services. Any purchases you make through Third-Party Websites will be through other websites and from other companies, and we take no responsibility whatsoever in relation to such purchases which are exclusively between you and the applicable third party. You agree and acknowledge that we do not endorse any Third-Party Content and you shall hold us harmless from any harm caused to you relating to or resulting in any way from any Third-Party Content or any contact with Third-Party Websites.
            </p>

            <h2>Privacy and Data Security</h2>
            <p>
              In order to provide you with the Services under these Terms and in accordance with our Privacy Policy, we will collect your personal information for identity verification purposes and to provide the Services to you. We may disclose any personal information that we collect about you in order to provide the Services to you and in compliance with applicable laws. Our Privacy Policy includes disclosures regarding how we collect, use, and disclose your personal information when you use our Services. Our Privacy Policy can be found here [www.computers4people.org/privacypolicy] and is part of and incorporated into these Terms.
            </p>
            <p>
              Our Services are operated within the United States. Unless expressly stated to the contrary, we make no representation that the Services are appropriate for, or will be appropriate or available for use in, other locations. All marketing or promotional materials accessible through the Services are solely directed to companies or other entities located in the United States. When you choose to access the Services from outside of the United States, you are responsible for compliance with any local, state, or national laws, including data protection laws, applicable to your use of the Services. By accessing or using the Services, you consent to the collection, use, storage, and transfer of information about you in and to the United States. Please be advised that the laws of the United States may not provide you with the same rights and protections as you may have under the data protection laws in your jurisdiction.
            </p>
            <p>
              Please be aware that data transmissions are never completely secure. You will be responsible for complying with any system requirements for the use of the Services, including maintaining any network connectivity required to access the Services, and the accuracy, quality, and integrity of any data that you provide to us. You agree to immediately notify us if you become aware of any unauthorized access to or use of the Services. We may, in our sole discretion, suspend your access to the Services in the event of any actual or suspected breach of security involving your use of the Services, including any unauthorized access, disclosure, acquisition, theft, loss or unavailability of your account. We reserve the right to periodically audit and monitor your use of the Services to ensure compliance with these Terms and applicable laws, and to maintain and improve the Services. You agree that we shall have no liability to you for any loss or corruption of any data that you make available to us, and you hereby waive any right of action against us arising from any such loss or corruption of such data.
            </p>
            <p>
              Further, we do not knowingly accept, request, or solicit information from children unless with parental consent. Therefore, in accordance with the U.S. Children’s Online Privacy Protection Act, if we receive actual knowledge that anyone under the age of thirteen (13) has provided personal information to us without the requisite and verifiable parental consent, we will delete that information from the Services as quickly as is reasonably practical.
            </p>

            <h2>Term and Termination</h2>
            <p>You may terminate these Terms, with or without cause and at any time, by discontinuing your use of the Services.</p>
            <p>
              We shall have the right immediately to terminate these Terms with or without cause and at any time, including without limitation, in the event of any breach by you of these Terms. We may discontinue or change the availability, functionality, features, content, or technical specifications of the Services (or any portion thereof), at any time in our sole discretion whether with or without notice. You further accept that such changes may result in your being unable to access the Services. We shall not be liable to you or any third party for the termination, suspension or modification of the Services, or any claims related thereto.
            </p>
            <p>Upon termination of these Terms by you or us, you must discontinue your use of the Services and promptly destroy all materials obtained from the Services and any copies thereof.</p>
            <p>
              WITHOUT LIMITING ANY OTHER PROVISION OF THESE TERMS, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF THE SERVICES (INCLUDING BLOCKING CERTAIN IP ADDRESSES), TO ANY PERSON FOR ANY REASON OR FOR NO REASON, INCLUDING WITHOUT LIMITATION FOR BREACH OF ANY REPRESENTATION, WARRANTY, OR COVENANT CONTAINED IN THESE TERMS OR OF ANY APPLICABLE LAW OR REGULATION. WE MAY TERMINATE YOUR USE OR PARTICIPATION IN THE SERVICES OR DELETE YOUR ACCOUNT AND ANY CONTENT OR INFORMATION THAT YOU MADE AVAILABLE TO US AT ANY TIME, WITHOUT WARNING, IN OUR SOLE DISCRETION. FOR CLARITY, THE FOREGOING DOES NOT LIMIT OUR RIGHT TO TAKE ANY APPROPRIATE LEGAL ACTION, INCLUDING WITHOUT LIMITATION PURSUING CIVIL, CRIMINAL, AND INJUNCTIVE REDRESS.
            </p>

            <h2>Indemnification</h2>
            <p>
              You agree, at your own cost and expense, to indemnify, defend, and hold harmless us and our affiliates and, and our and their respective owners, members, agents, directors, officers, employees, representatives, Suppliers, successors, and assigns (each, a “Company Party”, collectively, the “Company Parties”) against any claim, suit, action, or other proceeding from and against any and all claims, damages, liabilities, costs, and expenses, including reasonable attorneys’ and experts’ fees, arising out of or in connection with the Services, or any Third-Party Websites or Third-Party Content, including but not limited to: (i) any breach or violation of these Terms by you or someone using your device or account; (ii) any materials entered into or transmitted through the Services with the use of your device or account; (iii) the use of the Services by you or someone using your device or account; (iv) your activities in connection with the Services (or any portion thereof); (v) your access or use or any Third Party Websites or Third Party Content; (vi) a claim that any use of the Services by you or someone using your account or device infringes any Intellectual Property Right or other proprietary rights of any third party, or violates any right of privacy or publicity of any third party, is libelous or defamatory, or otherwise results in injury, harm or damage to any third party; (vii) your use or misuse of any user’s personal information, (viii) your gross negligence, willful misconduct or fraud, or (ix) your violations of applicable laws or regulations. The foregoing obligation will continue after you stop using the Services.
            </p>
            <p>
              We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which event you will fully cooperate with us in asserting any available defense.
            </p>

            <h2>Disclaimer of Warranties</h2>
            <p>
              YOU AGREE THAT YOUR USE OF THE SERVICES IS AT YOUR SOLE RISK AND ACKNOWLEDGE THAT THE SITE, THE SERVICES AND ALL CONTENT CONTAINED IN OR MADE AVAILABLE VIA THE SERVICES ARE PROVIDED “AS IS” AND “AS AVAILABLE.” WE MAKE NO, AND EXPRESSLY DISCLAIM ALL, WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, AS TO THE SITE OR THE SERVICES, INCLUDING, BUT NOT LIMITED TO, MERCHANTABILITY, NON-INFRINGEMENT, TITLE, TIMELINESS, ACCURACY, RELIABILITY, AVAILAIBILITY, SECURITY OR COMPLETENESS OF DATA, OR FITNESS FOR A PARTICULAR PURPOSE OR USE. YOUR SOLE REMEDY AGAINST US FOR DISSATISFACTION WITH THE SERVICES IS TO STOP USING THE SERVICES, AS APPLICABLE. THE FOREGOING LIMITATION OF RELIEF IS AN ESSENTIAL PART OF THE BARGIN BETWEEN YOU AND US UNDER THESE TERMS.
            </p>
            <p>
              We do not warrant that the Services are compatible with your equipment or that the Services, or e-mail sent by us or our representative, is free of errors or viruses, worms or “Trojan horses,” or any other harmful, invasive, or corrupted files, and is not liable for any damage you may suffer as a result of such destructive features. We will not be liable if, for any reason, all or part of the Services is ever unavailable. We reserve the right at any time and from time to time to modify or discontinue, temporarily or permanently, the Services, or any portion thereof, with or without notice, and we undertake no obligation to update, amend or clarify information on the Services, except as may be required by law.
            </p>
            <p>
              WE EXPRESSLY DISCLAIM ANY AND ALL LIABILITY, INCLUDING ANY EXPRESS OR IMPLIED WARRANTIES OF ANY KIND, WHETHER ORAL OR WRITTEN, EXPRESS OR IMPLIED, FOR ANY THIRD-PARTY WEBSITES AND THIRD-PARTY CONTENT. YOU ACKNOWLEDGE THAT NO REPRESENTATION HAS BEEN MADE BY US AS TO THE FITNESS OF ANY THIRD-PARTY WEBSITES OR THIRD-PARTY CONTENT.
            </p>
            <p>
              We are also not responsible for the reliability or continued availability of the telephone lines, wireless services, communications media, and equipment you use to access the Services or any access to the internet provided by or through the Services. You understand that we and/or Suppliers to the Services may choose at any time to inhibit or prohibit certain Content from being accessed under these Terms, even if you have already begun participating in a particular activity or utilizing a particular feature. Anything to the contrary herein set forth notwithstanding, no Company Party shall, directly or indirectly, be liable, in any way, to you or any other person for any: (i) inaccuracies or errors in or omissions from the Services; (ii) delays, errors, or interruptions in the transmission, delivery or provision of the Services; or (iii) loss or damage therefrom or occasioned thereby, or by any reason of nonperformance.
            </p>
            <p>
              In the event you have a dispute with one or more users of the Services, you release all Company Parties from any claims, damages, liabilities, costs, and expenses, including reasonable attorneys’ and experts’ fees, arising out of or in connection with such dispute.
            </p>

            <h2>Offline Services</h2>
            <p>
              You may be eligible to apply to register or register (as applicable) for certain of our Offline Services (whether hosted by our or our Suppliers). For clarity, submission of an application to use any of our Offline Services does not guarantee our approval for your participation in such Offline Services. We will provide you with a written notice of our approval or rejection of your application after we have fully evaluated your application at our sole discretion. If you register for any of our Offline Services, you agree to comply with any additional terms and conditions applicable for the specific Offline Service provided at registration. We and our Suppliers (as applicable) reserve the right to cancel or modify any Offline Services.
            </p>
            <p>
              If you choose to participate in our Offline Services, you do so of your own free will and accord, knowingly and voluntarily assuming all known or unknown risks associated with such activities. EXCEPT AS OTHERWISE EXPRESSLY SET FORTH IN THESE TERMS, AND TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WE ARE NOT RESPONSIBLE OR LIABLE, EITHER DIRECTLY OR INDIRECTLY, FOR ANY INJURY, ILLNESS, OR DAMAGES SUSTAINED FROM YOUR USE OF, OR INABILITY TO USE, ANY SERVICES OR FEATURES OF THE SERVICES, INCLUDING ANY CONTENT, OFFLINE SERVICES OR ACTIVITIES YOU ACCESS, LEARN ABOUT OR PERFORM THROUGH OUR SERVICES EVEN IF CAUSED IN WHOLE OR PART BY THE ACTION, INACTION OR NEGLIGENCE OF US OR OTHERS.
            </p>
            <p>
              Our Offline Services may be photographed, recorded, or filmed. By registering for our Offline Services, you grant us permission to use your likeness in promotional materials without compensation, unless you notify us in writing (using the contact information below) reasonably in advance to opt out.
            </p>
            <p>
              Any personal data collected during your applicable, registration or attendance of any Offline Services will be handled in accordance with our Privacy Policy. We may share such personal data with our Suppliers for the purpose of providing and improving our Offline Services.
            </p>

            <h2>Limitation of Liability</h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, UNDER NO CIRCUMSTANCES, INCLUDING BUT NOT LIMITED TO NEGLIGENCE, SHALL ANY COMPANY PARTY BE LIABLE TO YOU OR ANY THIRD PARTY FOR DIRECT, INDIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, PUNITIVE, OR EXEMPLARY DAMAGES EVEN IF WE OR THEY HAVE BEEN ADVISED SPECIFICALLY OF THE POSSIBILITY OF SUCH DAMAGES, ARISING FROM USE OF OR INABILITY TO USE THE SERVICES OR ANY THIRD-PARTY WEBSITES OR THIRD-PARTY CONTENT, OR ANY PROVISION OF THESE TERMS. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE AGGREGATE LIABILITY OF THE COMPANY PARTIES EXCEED THE GREATER OF ONE HUNDRED U.S. DOLLARS (U.S. $100.00) OR THE AMOUNT YOU PAID TO ANY COMPANY PARTY, IF ANY, IN THE PAST SIX MONTHS FOR THE SERVICES GIVING RISE TO THE CLAIM. THE LIMITATIONS OF THIS SECTION SHALL APPLY TO ANY THEORY OF LIABILITY, WHETHER BASED ON WARRANTY, CONTRACT, STATUTE, TORT (INCLUDING NEGLIGENCE) OR OTHERWISE, WHETHER OR NOT ANY COMPANY PARTIES HAVE BEEN INFORMED OF THE POSSIBILITY OF ANY SUCH DAMAGE, AND EVEN IF A REMEDY SET FORTH HEREIN IS FOUND TO HAVE FAILED OF ITS ESSENTIAL PURPOSE.
            </p>

            <h2>Dispute Resolution (Mandatory Arbitration; Class Action and Jury Trial Waiver)</h2>
            <p>
              YOU AND WE AGREE TO THE FOLLOWING DISPUTE RESOLUTIONS PROVISIONS, WHICH INCLUDES, WITHOUT LIMITATION, MANDATORY ARBITRATION, CLASS ACTION WAIVER, AND JURY TRIAL WAIVER PROVISIONS:
            </p>
            <p>
              <strong>MANDATORY ARBITRATION.</strong> You and we agree to resolve any cause of action, claim or dispute in any way arising out of or relating to these Terms or our Services, regardless of when the claim arose, even if it was before these Terms existed (each, a “Dispute”), through final and binding arbitration. You may opt out of arbitration within thirty (30) days of your first use of the Services by sending us notice to [info@computers4people.org] with the subject line “ARBITRATION OPT-OUT.”
            </p>
            <p>
              <strong>Informal Dispute Resolution.</strong> We would like to understand and try to address your concerns prior to formal legal action. Before either of us files a claim against the other, we both agree to try to resolve the Dispute informally. You agree to do so by sending us notice to [info@computers4people.org] with the subject line “DISPUTE NOTICE.” We will do so by sending you notice to the email address associated with your account. If you and we are unable to resolve a Dispute within sixty (60) days, either you or we have the right to initiate arbitration. You and we also both agree to attend an individual settlement conference if either party requests one during this time. Any statute of limitations will be tolled during this informal resolution process.
            </p>
            <p>
              <strong>Arbitration Forum.</strong> If you and we are unable to resolve the Dispute, either of you or we may commence arbitration with National Arbitration and Mediation (“NAM”) under its Comprehensive Dispute Resolution Rules and Procedures and/or Supplemental Rules for Mass Arbitration Filings, as applicable (available at https://www.namadr.com/resources/rules-fees-forms/). We will not seek attorneys’ fees and costs from you in arbitration unless the arbitrator determines that your claim is frivolous. The activities described in these Terms involve interstate commerce and the Federal Arbitration Act will govern the interpretation and enforcement of these arbitration terms in this Section 15 and any arbitration of a Dispute.
            </p>
            <p>
              <strong>Arbitration Procedures.</strong> The arbitration will be conducted by videoconference if possible, but if the arbitrator determines a hearing should be conducted in person, the location will be mutually agreed upon, in the county where you reside, or as determined by the arbitrator, unless the batch arbitration process applies. The arbitration will be conducted by a sole arbitrator. The arbitrator will be either a retired judge or an attorney licensed to practice law in the State of [New Jersey]. The arbitrator will have exclusive authority to resolve any Dispute, except the state or federal courts of the State of [New Jersey] have the authority to determine any Dispute about enforceability, validity of the class action waiver, or requests for public injunctive relief, as set out below. Any settlement offer amounts will not be disclosed to the arbitrator by either party until after the arbitrator determines the final award, if any. The arbitrator has the authority to grant motions dispositive of all or part of any Dispute.
            </p>
            <p>
              <strong>Exceptions.</strong> This Section 15 does not require informal dispute resolution or arbitration of the following claims: (i) individual claims brought in small claims court; and (ii) injunctive or other equitable relief to stop unauthorized use or abuse of the Services or Intellectual Property Rights infringement or misappropriation.
            </p>
            <p>
              <strong>CLASS ACTION AND JURY TRAIL WAIVERS.</strong> YOU AND WE AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR OUR INDIVIDUAL CAPACITY, AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS, CONSOLIDATED, OR REPRESENTATIVE PROCEEDING OR AS AN ASSOCIATION. Disputes will be resolved only on an individual basis and will not be joined or consolidated with any other proceedings that involve any claim or controversy of any other party. There shall be no right or authority for any dispute to be resolved on a class action basis, class arbitration basis, representative action basis, or on any basis involving disputes brought in a purported representative capacity on behalf of the general public, or other persons or entities similarly situated. The parties agree to sever and litigate in court any request for public injunctive relief after completing arbitration for the underlying claim and all other claims. This Section 15(f) does not prevent either party from participating in a class-wide settlement. You and we knowingly and irrevocably waive any right to trial by jury in any action, proceeding, or counterclaim.
            </p>
            <p>
              Any cause of action, claim or dispute relating in any way to these Terms or our Services (including your use thereof) must be commenced within one (1) year after such cause of action, claim or dispute arises.
            </p>
            <p>
              <strong>Batch Arbitration.</strong> If twenty-five (25) or more claimants represented by the same or similar counsel file demands for arbitration raising substantially similar Disputes within ninety (90) days of each other, then you and we agree that NAM will administer them in batches of up to fifty (50) claimants each (“Batch”), unless there are less than fifty (50) claimants in total or after batching, which will comprise a single Batch. NAM will administer each Batch as a single consolidated arbitration with one arbitrator, one set of arbitration fees, and one hearing held by videoconference or in a location decided by the arbitrator for each Batch. If any part of this Section 15(h) is found to be invalid or unenforceable as to a particular claimant or Batch, it will be severed and arbitrated in individual proceedings.
            </p>
            <p>
              <strong>Severability.</strong> If any part of this Section 15 is found to be illegal or unenforceable, the remainder will remain in effect, except that if a finding of partial illegality or unenforceability would allow class arbitration, class action, or representative action, this entire Section 15 will be unenforceable in its entirety.
            </p>

            <h2>Miscellaneous</h2>
            <p>
              <strong>Governing Law and Venue.</strong> These Terms shall be governed and construed in accordance with the laws of the United States and the State of [New Jersey], without giving effect to conflicts-of-law principles thereof. Except as provided in Section 15 above, you agree to submit to the personal jurisdiction of the state and federal courts located in the State of [New Jersey] with respect to any legal proceedings that may arise in connection with the Services or from a dispute as to the interpretation or breach of these Terms and hereby waive any objection to the propriety or convenience of venue in such courts.
            </p>
            <p>
              <strong>Electronic Communications.</strong> When you access or use the Services and when you communicate with us electronically, you consent to receive communications from us electronically and to electronically sign documents. You agree that all notices, disclosures, and other communications that we provide to you electronically satisfy any legal requirement that such communications be in writing. You agree that you have the ability to store such electronic communications such that they remain accessible to you in an unchanged form. We will retain a copy of any agreement or document you sign electronically, including through the Services, and you are responsible for retaining a copy of any agreement or document you sign electronically, including through the Services.
            </p>
            <p>
              <strong>Assignment; Delegation.</strong> You may not assign or transfer these Terms or the obligations or rights hereunder, including but not limited to the limited right for you to access and use the Services in accordance with these Terms. You acknowledge and agree that we may freely assign these Terms or delegate a portion or all of our responsibilities, obligations, and duties under or in connection with these Terms or the Services to an affiliated entity, Supplier, or any third party, which may discharge the responsibilities, obligations, and duties on our behalf.
            </p>
            <p>
              <strong>Parties; Third-Party Beneficiaries.</strong> You recognize that each Company Party has rights with respect to the Services, including the information and other items provided by such Company Party by reason of your use of the Services. These Terms shall be for the benefit of each applicable Company Party.
            </p>
            <p>
              <strong>Use of Trademarks and Other Marks or Rights.</strong> You may not use any trademarks, trade names, service marks, copyrights, or logos of any Company Party or their respective licensors in any manner which creates the impression that such items (i) belong to or are associated with you or indicate the sponsorship, endorsement or approval by any Company Party or any of their respective licensors; or (ii) are used with the consent of any Company Party or any of their respective licensors. You acknowledge that you have no ownership rights in or to any such items. You may not use such items to disparage any Company Party or their respective licensors, or its or their respective products or services, or in any manner (using commercially reasonable judgment) that may damage any goodwill in such items.
            </p>
            <p>
              <strong>Local Regulatory Restrictions.</strong> The Services are not directed to any person in any jurisdiction where (for any reason) the publication or availability of the Services is prohibited, and persons in respect of whom such prohibitions apply must not access the Services. Those who choose to access the Services from other locations do so at their own initiative and are responsible for compliance with local laws.
            </p>
            <p>
              <strong>Entire Agreement; Interpretations; Waiver.</strong> These Terms and any other terms and conditions on the Services, constitute the entire agreement between you and us and govern your access to and use of the Services. The section titles in these Terms are used solely for the convenience of you and us and have no legal or contractual significance. Our failure to exercise or enforce any right or provision of these Terms shall not constitute a waiver of such right or provision. If any provision of these Terms is found invalid or unenforceable, that provision will be enforced to the maximum extent permissible, and the other provisions of these Terms will remain in force.
            </p>
            <p>
              <strong>DMC Takedown Notice.</strong> If you believe that any content appearing on the Services has been copied in a way that constitutes copyright infringement, please forward the following information to the designated copyright agent named below:
            </p>
            <ul className="list-disc ml-6">
              <li>your name, address, telephone number, and email address;</li>
              <li>a description of the copyrighted work that you claim has been infringed;</li>
              <li>the exact URL or a description of where the alleged infringing material is located;</li>
              <li>a statement by you that you have a good faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law;</li>
              <li>an electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest; and</li>
              <li>a statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner’s behalf.</li>
            </ul>
            <p>
              The designated contact to receive notification of claimed infringement under Title II of the Digital Millennium Copyright Act is: [info@computers4people.org].
            </p>
            <p>
              <strong>Notice for California Users.</strong> Under California Civil Code Section 1789.3, California users of the Sites are entitled to the following specific consumer rights notice:  The Complaint Assistance Unit of the Division of Consumer Services of the California Department of Consumer Affairs may be contacted in writing at 1625 North Market Blvd., Suite N. 112, Sacramento, CA 95834, or by telephone at (916) 445-1254 or (800) 952-5210.
            </p>
            <p>
              <strong>Contact Us.</strong> If you have any questions or Feedback about the Services, please contact us at: [info@computers4people.org].
            </p>
          </article>
        </div>
      </div>
    </div>
  );
}
